# Generated by Django 4.2.2 on 2023-07-19 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=75, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('view_status', models.BooleanField(default=False, verbose_name='View Status')),
                ('status', models.CharField(choices=[('INFO', 'Information'), ('SUCS', 'Success'), ('WARN', 'Warning'), ('EROR', 'Error')], default='INFO', max_length=4, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
