# Generated by Django 4.2.2 on 2023-07-20 12:27

import app_chat.models.chat_room
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=75, verbose_name='Title')),
                ('is_group', models.BooleanField(default=False, verbose_name='Is Group')),
                ('is_ticket', models.BooleanField(default=True, verbose_name='Is Ticket')),
                ('room_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Room Id')),
                ('status', models.CharField(choices=[('AWF', 'Waiting For An Answer'), ('ABA', 'Has Been Answered'), ('CLS', 'Closed')], default='AWF', max_length=5, verbose_name='Status')),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MED', 'Medium'), ('HIG', 'High')], default='LOW', max_length=3, verbose_name='Priority')),
                ('members', models.ManyToManyField(related_name='user_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('message', models.TextField(verbose_name='Message')),
                ('file', models.FileField(upload_to=app_chat.models.chat_room.ticket_image_directory_path, verbose_name='Image')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_messages', to='app_chat.chatroom', verbose_name='Chat Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
