# Generated by Django 4.2.2 on 2023-07-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-create_at']},
        ),
    ]
