# Generated by Django 4.1.5 on 2023-12-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "LOW"), ("Medium", "Medium"), ("High", "High")],
                default="LOW",
                max_length=6,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("Waiting_For_An_Answer", "Waiting For An Answer"),
                    ("Has_Been_Answered", "Has Been Answered"),
                    ("Closed", "Closed"),
                ],
                default="Waiting_For_An_Answer",
                max_length=21,
                verbose_name="Status",
            ),
        ),
    ]
