# Generated by Django 4.1.5 on 2024-03-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_chat", "0003_alter_chatroom_priority_alter_chatroom_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="is_group",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="is_ticket",
        ),
    ]
