# Generated by Django 4.1.5 on 2024-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_chat", "0004_remove_chatroom_is_group_remove_chatroom_is_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
    ]
