# Generated by Django 4.1.5 on 2023-02-23 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_application', '0002_alter_application_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('occupation', models.CharField(choices=[('ACD', 'Academician'), ('GVE', 'Government Employee'), ('INE', 'Industrial Employee'), ('STU', 'Student'), ('OTR', 'Other')], max_length=3, verbose_name='Occupation')),
                ('organization', models.CharField(max_length=50, verbose_name='Organization')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_application.application', verbose_name='Application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
