# Generated by Django 4.1.5 on 2023-03-03 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0010_alter_application_tracking_id'),
        ('app_occupation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestoccupation',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_latest_occupation', to='app_application.application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='latestoccupation',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
