# Generated by Django 4.1.5 on 2023-12-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_occupation", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestoccupation",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("Other", "Other"),
                    ("Academician", "Academician"),
                    ("Government_Employee", "Government Employee"),
                    ("Industrial_Employee", "Industrial Employee"),
                    ("Student", "Student"),
                ],
                default="Other",
                max_length=19,
                verbose_name="Occupation",
            ),
        ),
    ]
