# Generated by Django 4.2.2 on 2023-07-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_occupation', '0002_alter_latestoccupation_application_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestoccupation',
            options={'ordering': ['-id'], 'verbose_name': 'Latest Occupation', 'verbose_name_plural': 'Latest Occupations'},
        ),
    ]
