# Generated by Django 4.2.1 on 2023-07-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_occupation', '0004_remove_latestoccupation_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestoccupation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='latestoccupation',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='latestoccupation',
            name='occupation',
            field=models.CharField(choices=[('OTR', 'Other'), ('ACD', 'Academician'), ('GVE', 'Government Employee'), ('INE', 'Industrial Employee'), ('STU', 'Student')], default='OTR', max_length=3, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='latestoccupation',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='latestoccupation',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Date'),
        ),
    ]
