# Generated by Django 4.1.5 on 2023-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
