# Generated by Django 4.1.5 on 2024-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0005_remove_user_agent_user_is_agent_user_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="passport_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Passport Number"
            ),
        ),
    ]
