# Generated by Django 4.1.5 on 2023-02-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_alter_address_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='english_status',
            field=models.CharField(choices=[('WEK', 'Weak'), ('GOD', 'Good'), ('EXT', 'Excellent')], default='GOD', max_length=3, verbose_name='English Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='persian_status',
            field=models.CharField(choices=[('WEK', 'Weak'), ('GOD', 'Good'), ('EXT', 'Excellent')], default='GOD', max_length=3, verbose_name='Persian Status'),
        ),
    ]
