# Generated by Django 4.2.2 on 2023-07-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_alter_address_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Agent Email'),
        ),
    ]
