# Generated by Django 4.2.2 on 2023-07-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_profile_phone_number_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=35, verbose_name='Country'),
        ),
    ]
