# Generated by Django 4.2.2 on 2023-07-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_alter_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
    ]
