# Generated by Django 4.1.5 on 2023-07-30 16:26

import app_user.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0015_alter_address_city_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=app_user.models.profile.profile_image_directory_path, verbose_name='Profile'),
        ),
    ]
