# Generated by Django 4.1.5 on 2023-11-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0016_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('prof', 'Prof'), ('staff', 'Staff'), ('karshenas', 'Karshenas')], default='nothing', max_length=9, verbose_name='Admin Role'),
        ),
    ]
