# Generated by Django 4.1.5 on 2023-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0017_user_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Age'),
        ),
    ]
