# Generated by Django 4.1.5 on 2023-11-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0019_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picurl',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Picture URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sub Code'),
        ),
    ]
