# Generated by Django 4.2.2 on 2023-07-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_education', '0002_programrequested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bachelordegree',
            options={'ordering': ['-id'], 'verbose_name': 'Bachelor Degree', 'verbose_name_plural': 'Bachelor Degrees'},
        ),
        migrations.AlterModelOptions(
            name='highschool',
            options={'ordering': ['-id'], 'verbose_name': 'High School', 'verbose_name_plural': 'High Schools'},
        ),
        migrations.AlterModelOptions(
            name='masterdegree',
            options={'ordering': ['-id'], 'verbose_name': 'MasterDegree', 'verbose_name_plural': 'Master Degrees'},
        ),
        migrations.AlterModelOptions(
            name='programrequested',
            options={'ordering': ['-id'], 'verbose_name': 'Program Request', 'verbose_name_plural': 'Program Requests'},
        ),
    ]
