# Generated by Django 4.2.2 on 2023-07-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_education', '0003_alter_bachelordegree_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelordegree',
            name='country',
            field=models.CharField(max_length=35, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='country',
            field=models.CharField(max_length=35, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='masterdegree',
            name='country',
            field=models.CharField(max_length=35, verbose_name='Country'),
        ),
    ]
