# Generated by Django 4.2.1 on 2023-07-26 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_education', '0004_alter_bachelordegree_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelordegree',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='bachelordegree',
            name='country',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='bachelordegree',
            name='date_of_graduation',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Graduation'),
        ),
        migrations.AlterField(
            model_name='bachelordegree',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field Of Study'),
        ),
        migrations.AlterField(
            model_name='bachelordegree',
            name='gpa',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='bachelordegree',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='University'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='country',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='date_of_graduation',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Graduation'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field Of Study'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='gpa',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='masterdegree',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='masterdegree',
            name='country',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='masterdegree',
            name='date_of_graduation',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Graduation'),
        ),
        migrations.AlterField(
            model_name='masterdegree',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field Of Study'),
        ),
        migrations.AlterField(
            model_name='masterdegree',
            name='gpa',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='masterdegree',
            name='university',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='University'),
        ),
        migrations.DeleteModel(
            name='ProgramRequested',
        ),
    ]
