# Generated by Django 4.1.5 on 2023-02-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='cfd61d47be4c', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
