# Generated by Django 4.1.5 on 2023-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0002_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='0d216baf6588', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
