# Generated by Django 4.1.5 on 2023-12-28 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_application", "0003_alter_application_faculty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Is Enabled"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_referral",
                        to="app_application.application",
                        verbose_name="Application",
                    ),
                ),
                (
                    "destination_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_user_referral",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destination User",
                    ),
                ),
                (
                    "origin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_user_referral",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Origin User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
