# Generated by Django 4.1.5 on 2023-02-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0003_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='985ceee6658c', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
