# Generated by Django 4.1.5 on 2023-02-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0004_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='a0cc3d9655b3', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
