# Generated by Django 4.1.5 on 2023-02-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0005_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('CRNT', 'Current'), ('ACPT', 'Accepted'), ('RJCT', 'Rejected'), ('NTET', 'NeedToEdit')], default='CRNT', max_length=4, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='1c4c8c563fc9', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
