# Generated by Django 4.1.5 on 2023-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0006_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='6c9aef90be4d', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
