# Generated by Django 4.1.5 on 2024-01-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_application", "0007_alter_application_faculty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent Email",
            ),
        ),
    ]
