# Generated by Django 4.1.5 on 2023-02-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0007_alter_application_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comments',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='b404c23e15e9', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
