# Generated by Django 4.1.5 on 2023-03-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0009_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='fa22cfaea154', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
