# Generated by Django 4.1.5 on 2024-03-24 08:36

import app_application.models.application
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_application", "0009_alter_timeline_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="application_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=app_application.models.application.application_file_directory_path,
                verbose_name="Application File",
            ),
        ),
    ]
