# Generated by Django 4.1.5 on 2024-03-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_application", "0010_application_application_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="financial_self_support",
            field=models.BooleanField(
                default=False, verbose_name="Financial Self Support"
            ),
        ),
    ]
