# Generated by Django 4.1.5 on 2023-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0010_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='dc0fdedd7e9d', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
