# Generated by Django 4.2.2 on 2023-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0012_alter_application_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='cca217328131', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
