# Generated by Django 4.2.2 on 2023-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0013_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='70e4a891b033', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
