# Generated by Django 4.2.2 on 2023-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0017_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='1d75956b4f6a', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
