# Generated by Django 4.2.2 on 2023-07-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0020_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='1f000c1e6d80', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
