# Generated by Django 4.2.1 on 2023-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0022_application_degree_application_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='3da3362919fc', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
