# Generated by Django 4.2.1 on 2023-07-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0024_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='17b8c2c81252', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
