# Generated by Django 4.2.1 on 2023-07-29 16:12

import app_application.models.documents
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0028_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='c224ed239439', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='bachelor_degree',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Bachelor Degree'),
        ),
        migrations.AlterField(
            model_name='document',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Curriculum Vitae'),
        ),
        migrations.AlterField(
            model_name='document',
            name='high_school_certificate',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='High School Certificate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='master_degree',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Master Degree'),
        ),
        migrations.AlterField(
            model_name='document',
            name='personal_photo',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Personal photo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='supporting_letter',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Supporting Letter'),
        ),
        migrations.AlterField(
            model_name='document',
            name='trans_script_bachelor_degree',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Trans Script Bachelor Degree'),
        ),
        migrations.AlterField(
            model_name='document',
            name='trans_script_high_school_certificate',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Trans Script High School Certificate'),
        ),
        migrations.AlterField(
            model_name='document',
            name='trans_script_master_degree',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Trans Script Master Degree'),
        ),
        migrations.AlterField(
            model_name='document',
            name='valid_passport',
            field=models.FileField(blank=True, null=True, upload_to=app_application.models.documents.document_image_directory_path, validators=[utils.validators.validate_image_file], verbose_name='Valid'),
        ),
    ]
