# Generated by Django 4.1.5 on 2023-07-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0031_alter_application_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='c15d9b5fff99', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
