# Generated by Django 4.1.5 on 2023-07-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0032_alter_application_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='faculty_status',
            field=models.CharField(choices=[('CRNT', 'Current'), ('ACPT', 'Accepted'), ('RJCT', 'Rejected'), ('NTET', 'NeedToEdit')], default='CRNT', max_length=4, verbose_name='Faculty Status'),
        ),
        migrations.AddField(
            model_name='application',
            name='university_status',
            field=models.CharField(choices=[('CRNT', 'Current'), ('ACPT', 'Accepted'), ('RJCT', 'Rejected'), ('NTET', 'NeedToEdit')], default='CRNT', max_length=4, verbose_name='University Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='edab19dc21c0', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
