# Generated by Django 4.1.5 on 2023-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0033_remove_application_status_application_faculty_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='1a088ce47fcf', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
