# Generated by Django 4.1.5 on 2023-07-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0034_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='541eb512b69c', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
