# Generated by Django 4.1.5 on 2023-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0035_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='0174a751a21e', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
    ]
