# Generated by Django 4.1.5 on 2023-08-20 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_application', '0036_alter_application_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='tracking_id',
            field=models.CharField(default='4c37645e3b43', max_length=12, unique=True, verbose_name='Tracking ID'),
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('status', models.CharField(choices=[('CONF', 'Confirmation'), ('REJC', 'Rejection'), ('NFIN', 'Investigation')], max_length=4, verbose_name='Status')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_timeline', to='app_application.application', verbose_name='Application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_timeline', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
