# Generated by Django 4.1.5 on 2023-09-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_application", "0037_alter_application_tracking_id_timeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="faculty_status",
            field=models.CharField(
                choices=[
                    ("NOCO", "Not Completed"),
                    ("CRNT", "Current"),
                    ("ACPT", "Accepted"),
                    ("RJCT", "Rejected"),
                    ("NTET", "NeedToEdit"),
                ],
                default="NOCO",
                max_length=4,
                verbose_name="Faculty Status",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="tracking_id",
            field=models.CharField(
                default="9142ae804b93",
                max_length=12,
                unique=True,
                verbose_name="Tracking ID",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="university_status",
            field=models.CharField(
                choices=[
                    ("NOCO", "Not Completed"),
                    ("CRNT", "Current"),
                    ("ACPT", "Accepted"),
                    ("RJCT", "Rejected"),
                    ("NTET", "NeedToEdit"),
                ],
                default="NOCO",
                max_length=4,
                verbose_name="University Status",
            ),
        ),
    ]
