# Generated by Django 4.1.5 on 2023-09-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_application", "0038_alter_application_faculty_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="tracking_id",
            field=models.CharField(
                max_length=12, unique=True, verbose_name="Tracking ID"
            ),
        ),
    ]
