# Generated by Django 4.1.5 on 2023-11-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_application', '0039_alter_application_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='title',
        ),
    ]
