# Generated by Django 4.1.5 on 2023-12-20 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_admin", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="fields",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Fields"
            ),
        ),
        migrations.AddField(
            model_name="admin",
            name="schools",
            field=models.CharField(default=2, max_length=128, verbose_name="Schools"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="admin",
            name="role",
            field=models.CharField(
                choices=[
                    ("faculty_director", "Faculty Director"),
                    ("department_head", "Department Head"),
                    ("department_member", "Department Member"),
                ],
                default="department_member",
                max_length=17,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_admin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
